<template>
  <div>
    <h2 id="api-modal-props">Modal 属性</h2>
    <table class="api-props">
      <thead>
        <tr>
          <th width="200">属性</th>
          <th width="345">类型</th>
          <th width="100">默认值</th>
          <th width="80">必填</th>
          <th>说明</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>defaultVisible</td>
          <td>Boolean</td>
          <td>false</td>
          <td>N</td>
          <td>对话框默认是否可见（非受控模式）</td>
        </tr>
        <tr>
          <td>visible</td>
          <td>Boolean</td>
          <td>--</td>
          <td>N</td>
          <td>对话框是否可见（受控模式），可以使用 <code>v-model</code> 双向绑定</td>
        </tr>
        <tr>
          <td>icon</td>
          <td>String | RenderFunction | Slot</td>
          <td>--</td>
          <td>N</td>
          <td>标题左侧的图标类型/图标</td>
        </tr>
        <tr>
          <td>title</td>
          <td>String | RenderFunction | Slot</td>
          <td>--</td>
          <td>N</td>
          <td>对话框标题</td>
        </tr>
        <tr>
          <td>footer</td>
          <td>Boolean | String | RenderFunction | Slot</td>
          <td>--</td>
          <td>N</td>
          <td>对话框底部内容；当不需要底部按钮时，可以设为 <code>false</code></td>
        </tr>
        <tr>
          <td>showCancelButton</td>
          <td>Boolean</td>
          <td>true</td>
          <td>N</td>
          <td>是否显示取消按钮</td>
        </tr>
        <tr>
          <td>cancelButtonProps</td>
          <td>ButtonProps</td>
          <td>--</td>
          <td>N</td>
          <td>自定义取消按钮的属性</td>
        </tr>
        <tr>
          <td>cancelText</td>
          <td>String</td>
          <td>取消</td>
          <td>N</td>
          <td>取消按钮文字</td>
        </tr>
        <tr>
          <td>showOkButton</td>
          <td>Boolean</td>
          <td>true</td>
          <td>N</td>
          <td>是否显示确定按钮</td>
        </tr>
        <tr>
          <td>okButtonProps</td>
          <td>ButtonProps</td>
          <td>--</td>
          <td>N</td>
          <td>自定义确定按钮的属性</td>
        </tr>
        <tr>
          <td>okText</td>
          <td>String</td>
          <td>确定</td>
          <td>N</td>
          <td>确定按钮文字</td>
        </tr>
        <tr>
          <td>autofocusButton</td>
          <td>String</td>
          <td>--</td>
          <td>N</td>
          <td>指定自动获得焦点的按钮，可选值为 <code>cancel</code>、<code>ok</code> 或者不设</td>
        </tr>
        <tr>
          <td>closable</td>
          <td>Boolean</td>
          <td>true</td>
          <td>N</td>
          <td>是否显示右上角的关闭按钮</td>
        </tr>
        <tr>
          <td>closeText</td>
          <td>String</td>
          <td>--</td>
          <td>N</td>
          <td>关闭按钮文字</td>
        </tr>
        <tr>
          <td>width</td>
          <td>String | Number</td>
          <td>480</td>
          <td>N</td>
          <td>对话框宽度；对话框的宽度是响应式的，当屏幕宽度小于 <code>768px</code> 时，宽度会被强制设为 <code>auto</code></td>
        </tr>
        <tr>
          <td>top</td>
          <td>String | Number</td>
          <td>128</td>
          <td>N</td>
          <td>对话框距离页面顶部的距离，垂直居中或全屏显示对话框时该属性无效</td>
        </tr>
        <tr>
          <td>centered</td>
          <td>Boolean</td>
          <td>true</td>
          <td>N</td>
          <td>是否垂直居中显示对话框</td>
        </tr>
        <tr>
          <td>fullscreen</td>
          <td>Boolean</td>
          <td>false</td>
          <td>N</td>
          <td>是否全屏显示对话框</td>
        </tr>
        <tr>
          <td>draggable</td>
          <td>Boolean</td>
          <td>false</td>
          <td>N</td>
          <td>是否支持拖动，全屏显示状态下不支持</td>
        </tr>
        <tr>
          <td>backdrop</td>
          <td>Boolean</td>
          <td>true</td>
          <td>N</td>
          <td>是否显示背景遮罩</td>
        </tr>
        <tr>
          <td>clickBackdropToClose</td>
          <td>Boolean</td>
          <td>true</td>
          <td>N</td>
          <td>点击背景遮罩是否关闭对话框</td>
        </tr>
        <tr>
          <td>escToClose</td>
          <td>Boolean</td>
          <td>true</td>
          <td>N</td>
          <td>按下 ESC 键关闭对话框</td>
        </tr>
        <tr>
          <td>destroyOnClose</td>
          <td>Boolean</td>
          <td>false</td>
          <td>N</td>
          <td>关闭时销毁对话框内容（对话框里的子元素）</td>
        </tr>
        <tr>
          <td>getPopupContainer</td>
          <td>String | HTMLElement</td>
          <td>body</td>
          <td>N</td>
          <td>指定对话框挂载的 HTML 节点</td>
        </tr>
        <tr>
          <td>class</td>
          <td>String</td>
          <td>--</td>
          <td>N</td>
          <td>自定义对话框样式类名</td>
        </tr>
        <tr>
          <td>style</td>
          <td>CSSProperties</td>
          <td>--</td>
          <td>N</td>
          <td>自定义对话框样式</td>
        </tr>
        <tr>
          <td>headerStyle</td>
          <td>CSSProperties</td>
          <td>--</td>
          <td>N</td>
          <td>自定义对话框头部样式</td>
        </tr>
        <tr>
          <td>bodyStyle</td>
          <td>CSSProperties</td>
          <td>--</td>
          <td>N</td>
          <td>自定义对话框内容部分样式</td>
        </tr>
        <tr>
          <td>footerStyle</td>
          <td>CSSProperties</td>
          <td>--</td>
          <td>N</td>
          <td>自定义对话框底部样式</td>
        </tr>
        <tr>
          <td>backdropClassName</td>
          <td>String</td>
          <td>--</td>
          <td>N</td>
          <td>自定义背景遮罩样式类名</td>
        </tr>
        <tr>
          <td>backdropStyle</td>
          <td>CSSProperties</td>
          <td>--</td>
          <td>N</td>
          <td>自定义背景遮罩样式</td>
        </tr>
      </tbody>
    </table>
    <h2 id="api-modal-events">Modal 事件</h2>
    <table class="api-events">
      <thead>
        <tr>
          <th width="200">事件名</th>
          <th width="345">类型</th>
          <th width="100">回调参数</th>
          <th>说明</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>update:visible</td>
          <td>Function</td>
          <td>visible</td>
          <td>可见状态发生变化时触发的事件回调，可以使用 <code>v-model</code> 双向绑定</td>
        </tr>
        <tr>
          <td>change</td>
          <td>Function</td>
          <td>visible</td>
          <td>可见状态发生变化时触发的事件回调</td>
        </tr>
        <tr>
          <td>cancel</td>
          <td>Function</td>
          <td>--</td>
          <td>点击取消按钮（或右上角关闭按钮、背景遮罩）的事件回调</td>
        </tr>
        <tr>
          <td>ok</td>
          <td>Function</td>
          <td>--</td>
          <td>点击确定按钮的事件回调</td>
        </tr>
        <tr>
          <td>beforeOpen</td>
          <td>Function</td>
          <td>--</td>
          <td>对话框打开前触发的事件回调</td>
        </tr>
        <tr>
          <td>open</td>
          <td>Function</td>
          <td>--</td>
          <td>对话框打开时触发的事件回调</td>
        </tr>
        <tr>
          <td>afterOpen</td>
          <td>Function</td>
          <td>--</td>
          <td>对话框打开后（打开动画完成后）触发的事件回调</td>
        </tr>
        <tr>
          <td>beforeClose</td>
          <td>Function</td>
          <td>--</td>
          <td>对话框关闭前触发的事件回调</td>
        </tr>
        <tr>
          <td>close</td>
          <td>Function</td>
          <td>--</td>
          <td>对话框关闭时触发的事件回调</td>
        </tr>
        <tr>
          <td>afterClose</td>
          <td>Function</td>
          <td>--</td>
          <td>对话框关闭后（关闭动画完成后）触发的事件回调</td>
        </tr>
      </tbody>
    </table>
    <h2 id="api-modal-methods">Modal 静态方法</h2>
    <p>除了标准组件的使用方式，<code>Modal</code> 组件还提供了一些静态方法，可以通过以下三种方式使用：</p>
    <ul>
      <li>通过 <code>this.$modal</code> 调用</li>
      <li>在 <code>Composition API</code> 中，通过 <code>getCurrentInstance().appContext.config.globalProperties.$modal</code> 调用</li>
      <li>导入 <code>Modal</code>，通过 <code>Modal</code> 本身调用，如上示例</li>
    </ul>
    <p>静态方法及其参数如下所示：</p>
    <ul>
      <li><code>Modal.info(config)</code></li>
      <li><code>Modal.warning(config)</code></li>
      <li><code>Modal.success(config)</code></li>
      <li><code>Modal.error(config)</code></li>
      <li><code>Modal.confirm(config)</code></li>
    </ul>
    <p>其中 <code>config</code> 对象的属性如下所示：</p>
    <table class="api-props">
      <thead>
        <tr>
          <th width="200">选项</th>
          <th width="345">类型</th>
          <th width="100">默认值</th>
          <th width="80">必填</th>
          <th>说明</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>icon</td>
          <td>String | RenderFunction</td>
          <td>--</td>
          <td>N</td>
          <td>自定义图标类型/图标</td>
        </tr>
        <tr>
          <td>title</td>
          <td>String | RenderFunction</td>
          <td>--</td>
          <td>N</td>
          <td>对话框标题</td>
        </tr>
        <tr>
          <td>description</td>
          <td>String | RenderFunction</td>
          <td>--</td>
          <td>N</td>
          <td>对话框描述内容</td>
        </tr>
        <tr>
          <td>cancelButtonProps</td>
          <td>ButtonProps</td>
          <td>--</td>
          <td>N</td>
          <td>自定义取消按钮的属性，该选项仅在 <code>confirm</code> 对话框中有效</td>
        </tr>
        <tr>
          <td>cancelText</td>
          <td>String</td>
          <td>取消</td>
          <td>N</td>
          <td>取消按钮文字，该选项仅在 <code>confirm</code> 对话框中有效</td>
        </tr>
        <tr>
          <td>okButtonProps</td>
          <td>ButtonProps</td>
          <td>--</td>
          <td>N</td>
          <td>自定义确定按钮的属性</td>
        </tr>
        <tr>
          <td>okText</td>
          <td>String</td>
          <td>确定</td>
          <td>N</td>
          <td>确定按钮文字</td>
        </tr>
        <tr>
          <td>autofocusButton</td>
          <td>String</td>
          <td>--</td>
          <td>N</td>
          <td>指定自动获得焦点的按钮，可选值为 <code>cancel</code>、<code>ok</code> 或者不设</td>
        </tr>
        <tr>
          <td>width</td>
          <td>String | Number</td>
          <td>360</td>
          <td>N</td>
          <td>对话框宽度；对话框的宽度是响应式的，当屏幕宽度小于 <code>768px</code> 时，宽度会被强制设为 <code>auto</code></td>
        </tr>
        <tr>
          <td>top</td>
          <td>String | Number</td>
          <td>128</td>
          <td>N</td>
          <td>对话框距离页面顶部的距离，垂直居中或全屏显示对话框时该属性无效</td>
        </tr>
        <tr>
          <td>centered</td>
          <td>Boolean</td>
          <td>true</td>
          <td>N</td>
          <td>是否垂直居中显示对话框</td>
        </tr>
        <tr>
          <td>backdrop</td>
          <td>Boolean</td>
          <td>true</td>
          <td>N</td>
          <td>是否显示背景遮罩</td>
        </tr>
        <tr>
          <td>clickBackdropToClose</td>
          <td>Boolean</td>
          <td>false</td>
          <td>N</td>
          <td>点击背景遮罩是否关闭对话框</td>
        </tr>
        <tr>
          <td>escToClose</td>
          <td>Boolean</td>
          <td>false</td>
          <td>N</td>
          <td>按下 ESC 键关闭对话框</td>
        </tr>
        <tr>
          <td>destroyOnClose</td>
          <td>Boolean</td>
          <td>false</td>
          <td>N</td>
          <td>关闭时销毁对话框内容（对话框里的子元素）</td>
        </tr>
        <tr>
          <td>getPopupContainer</td>
          <td>String | HTMLElement</td>
          <td>body</td>
          <td>N</td>
          <td>指定对话框挂载的 HTML 节点</td>
        </tr>
        <tr>
          <td>class</td>
          <td>String</td>
          <td>--</td>
          <td>N</td>
          <td>自定义对话框样式类名</td>
        </tr>
        <tr>
          <td>style</td>
          <td>CSSProperties</td>
          <td>--</td>
          <td>N</td>
          <td>自定义对话框样式</td>
        </tr>
        <tr>
          <td>bodyStyle</td>
          <td>CSSProperties</td>
          <td>--</td>
          <td>N</td>
          <td>自定义对话框内容部分样式</td>
        </tr>
        <tr>
          <td>footerStyle</td>
          <td>CSSProperties</td>
          <td>--</td>
          <td>N</td>
          <td>自定义对话框底部样式</td>
        </tr>
        <tr>
          <td>backdropClassName</td>
          <td>String</td>
          <td>--</td>
          <td>N</td>
          <td>自定义背景遮罩样式类名</td>
        </tr>
        <tr>
          <td>backdropStyle</td>
          <td>CSSProperties</td>
          <td>--</td>
          <td>N</td>
          <td>自定义背景遮罩样式</td>
        </tr>
        <tr>
          <td>onCancel</td>
          <td>Function</td>
          <td>--</td>
          <td>N</td>
          <td>点击取消按钮的事件回调</td>
        </tr>
        <tr>
          <td>onOk</td>
          <td>Function</td>
          <td>--</td>
          <td>N</td>
          <td>点击确定按钮的事件回调</td>
        </tr>
        <tr>
          <td>onBeforeOpen</td>
          <td>Function</td>
          <td>--</td>
          <td>N</td>
          <td>对话框打开前触发的事件回调</td>
        </tr>
        <tr>
          <td>onOpen</td>
          <td>Function</td>
          <td>--</td>
          <td>N</td>
          <td>对话框打开时触发的事件回调</td>
        </tr>
        <tr>
          <td>onAfterOpen</td>
          <td>Function</td>
          <td>--</td>
          <td>N</td>
          <td>对话框打开后（打开动画完成后）触发的事件回调</td>
        </tr>
        <tr>
          <td>onBeforeClose</td>
          <td>Function</td>
          <td>--</td>
          <td>N</td>
          <td>对话框关闭前触发的事件回调</td>
        </tr>
        <tr>
          <td>onClose</td>
          <td>Function</td>
          <td>--</td>
          <td>N</td>
          <td>对话框关闭时触发的事件回调</td>
        </tr>
        <tr>
          <td>onAfterClose</td>
          <td>Function</td>
          <td>--</td>
          <td>N</td>
          <td>对话框关闭后（关闭动画完成后）触发的事件回调</td>
        </tr>
      </tbody>
    </table>
    <p>调用静态方法将会返回当前对话框的引用，可以通过该引用更新和关闭对话框：</p>
    <ul>
      <li><code>modal.update(config)</code></li>
      <li><code>modal.close()</code></li>
    </ul>
  </div>
</template>